name: weath_i_wear
description: "Weather Project for Mobile Programming Course"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: DEBROSEE
      fonts:
        - asset: assets/fonts/DEBROSEE.ttf

  uses-material-design: true
  assets:
    - assets/startscreenBackground.jpeg
